### ISSUE TITLE
[Flat-orange] Large space/padding under the input field

### ISSUE THREAD

**Issue by Spheerys** [davatorium/rofi-themes#36]
Since few days (after a rofi update?) my rofi window has a very large space under the input field :

![rofi-bug](https://user-images.githubusercontent.com/2228364/60248404-dd933400-98c2-11e9-9269-4b45415ce27f.png)

I'm using the official flat-orange theme and I don't understand how to remove this space.

**Comment by jcruse03** [comment]
+1 Same issue

**Comment by dannycolin** [comment]
You can resolve that bug by modifying the following line :

`[inputbar, message, sidebar, listview]` to `[inputbar, message, mode-switcher, listview]` in `#window`.

**Comment by Spheerys** [comment]
Thanks you, it works !!
